apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-exp
spec:
  destination:
    name: 'argo-exp'
    namespace: argo-exp
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/
    repoURL: 'https://github.com/devjadeja-simform/argocd-experiment'
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2